version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3000'
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
  test:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    command: ['npm', 'run', 'test']
